// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using sealHkthon.Entities.MinhMN.Models;

//namespace sealHkthon.Repositories.MinhMN.Models;
namespace sealHkthon.Repositories.MinhMN.DBContext;

public partial class PRN222_HACKATHONContext : DbContext
{
    public PRN222_HACKATHONContext()
    {
    }

    public PRN222_HACKATHONContext(DbContextOptions<PRN222_HACKATHONContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CategoriesHungDt> CategoriesHungDts { get; set; }

    public virtual DbSet<CriteriaItemsMinhMN> CriteriaItemsMinhMNs { get; set; }

    public virtual DbSet<CriteriaTemplateSetsMinhMN> CriteriaTemplateSetsMinhMNs { get; set; }

    public virtual DbSet<EventsThuanVct> EventsThuanVcts { get; set; }

    public virtual DbSet<JudgeScoresKhanhLq> JudgeScoresKhanhLqs { get; set; }

    public virtual DbSet<PrizeCategoriesSonNpx> PrizeCategoriesSonNpxes { get; set; }

    public virtual DbSet<PrizesSonNpx> PrizesSonNpxes { get; set; }

    public virtual DbSet<RoundsThuanVct> RoundsThuanVcts { get; set; }

    public virtual DbSet<SubmissionsKhanhLq> SubmissionsKhanhLqs { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<TeamMembersThangvlq> TeamMembersThangvlqs { get; set; }

    public virtual DbSet<TeamsHungDt> TeamsHungDts { get; set; }

    public virtual DbSet<TeamsThangvlq> TeamsThangvlqs { get; set; }


    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-3FROHFJA\\SQLEXPRESS;Initial Catalog=PRN222_HACKATHON;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CategoriesHungDt>(entity =>
        {
            entity.HasKey(e => e.CategoryHungDtid).HasName("PK__Categori__459C7E59FCD94CB5");

            entity.ToTable("CategoriesHungDT");

            entity.Property(e => e.CategoryHungDtid).HasColumnName("CategoryHungDTId");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status).HasDefaultValue(1);
        });

        modelBuilder.Entity<CriteriaTemplateSetsMinhMN>(entity =>
        {
            entity.HasKey(e => e.criteriaSetIdMinhMN).HasName("PK_CriteriaTemplateSets_MinhMN");

            entity.ToTable("CriteriaTemplateSets_MinhMN");

            entity.Property(e => e.criteriaSetIdMinhMN).HasColumnName("CriteriaSetIdMinhMN");
            entity.Property(e => e.criteriaSetName)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("CriteriaSetName");
            entity.Property(e => e.description)
                .HasMaxLength(1000)
                .HasColumnName("Description");
            entity.Property(e => e.isDefault)
                .HasDefaultValue(false)
                .HasColumnName("IsDefault");
            entity.Property(e => e.createdAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("CreatedAt");
        });

        modelBuilder.Entity<CriteriaItemsMinhMN>(entity =>
        {
            entity.HasKey(e => e.CriteriaIdMinhMN).HasName("PK_CriteriaItems_MinhMN");

            entity.ToTable("CriteriaItems_MinhMN");

            entity.Property(e => e.CriteriaIdMinhMN).HasColumnName("CriteriaIdMinhMN");
            entity.Property(e => e.CriteriaSetIdMinhMN).HasColumnName("CriteriaSetIdMinhMN");
            entity.Property(e => e.CriteriaName)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("CriteriaName");
            entity.Property(e => e.Description)
                .HasMaxLength(1000)
                .HasColumnName("Description");
            entity.Property(e => e.Weight).HasColumnName("Weight");
            entity.Property(e => e.MaxScore).HasColumnName("MaxScore");

            entity.HasOne(d => d.CriteriaTemplateSetsMinhMN)
                .WithMany(p => p.CriteriaItemsMinhMNs)
                .HasForeignKey(d => d.CriteriaSetIdMinhMN)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CriteriaItems_CriteriaTemplateSets_MinhMN");
        });

        modelBuilder.Entity<EventsThuanVct>(entity =>
        {
            entity.HasKey(e => e.EventThuanVctid).HasName("PK__Events__95EC05B3CEE289A6");

            entity.ToTable("EventsThuanVCT");

            entity.Property(e => e.EventThuanVctid).HasColumnName("EventThuanVCTId");
            entity.Property(e => e.EventName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PublishDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<JudgeScoresKhanhLq>(entity =>
        {
            entity.HasKey(e => e.ScoreId).HasName("PK__judge_sc__8CA1905024AC24A2");

            entity.ToTable("judge_scores_KhanhLQ");

            entity.Property(e => e.ScoreId).HasColumnName("score_id");
            entity.Property(e => e.CriterionName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("criterion_name");
            entity.Property(e => e.IsFinalized)
                .HasDefaultValue(false)
                .HasColumnName("is_finalized");
            entity.Property(e => e.JudgeName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("judge_name");
            entity.Property(e => e.Score)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("score");
            entity.Property(e => e.ScoredAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("scored_at");
            entity.Property(e => e.SubmissionId).HasColumnName("submission_id");

            entity.HasOne(d => d.Submission).WithMany(p => p.JudgeScoresKhanhLqs)
                .HasForeignKey(d => d.SubmissionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_judge_scores_submission_KhanhLQ");
        });

        modelBuilder.Entity<PrizeCategoriesSonNpx>(entity =>
        {
            entity.HasKey(e => e.PrizeCategorySonNpxid).HasName("PK__PrizeCat__B0009CAADF40F02F");

            entity.ToTable("PrizeCategoriesSonNPX");

            entity.Property(e => e.PrizeCategorySonNpxid).HasColumnName("PrizeCategorySonNPXId");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.EventSonNpxid).HasColumnName("EventSonNPXId");
            entity.Property(e => e.Status).HasDefaultValue(1);
        });

        modelBuilder.Entity<PrizesSonNpx>(entity =>
        {
            entity.HasKey(e => e.PrizeSonNpxid).HasName("PK__PrizesSo__CD0C274231B6A11F");

            entity.ToTable("PrizesSonNPX");

            entity.Property(e => e.PrizeSonNpxid).HasColumnName("PrizeSonNPXId");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PrizeCategorySonNpxid).HasColumnName("PrizeCategorySonNPXId");
            entity.Property(e => e.PrizeName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Quantity).HasDefaultValue(1);
            entity.Property(e => e.ValueAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.PrizeCategorySonNpx).WithMany(p => p.PrizesSonNpxes)
                .HasForeignKey(d => d.PrizeCategorySonNpxid)
                .HasConstraintName("FK_Prize_PrizeCategory");
        });

        modelBuilder.Entity<RoundsThuanVct>(entity =>
        {
            entity.HasKey(e => e.RoundThuanVctid).HasName("PK__Rounds__890D09B98A056612");

            entity.ToTable("RoundsThuanVCT");

            entity.Property(e => e.RoundThuanVctid).HasColumnName("RoundThuanVCTId");
            entity.Property(e => e.Deadline).HasColumnType("datetime");
            entity.Property(e => e.EventThuanVctid).HasColumnName("EventThuanVCTId");
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.RoundName)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.EventThuanVct).WithMany(p => p.RoundsThuanVcts)
                .HasForeignKey(d => d.EventThuanVctid)
                .HasConstraintName("FK_Rounds_Events_ThuanVCT");
        });

        modelBuilder.Entity<SubmissionsKhanhLq>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("PK__submissi__9B535595110F36C8");

            entity.ToTable("submissions_KhanhLQ");

            entity.Property(e => e.SubmissionId).HasColumnName("submission_id");
            entity.Property(e => e.FinalScore)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("final_score");
            entity.Property(e => e.IsApproved)
                .HasDefaultValue(false)
                .HasColumnName("is_approved");
            entity.Property(e => e.RepositoryUrl)
                .HasMaxLength(1000)
                .HasColumnName("repository_url");
            entity.Property(e => e.SubmittedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("submitted_at");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("team_name");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TeamMembersThangvlq>(entity =>
        {
            entity.HasKey(e => e.MemberIdThangvlq).HasName("PK__team_mem__C2B911E4B1EB7DC1");

            entity.ToTable("team_members_Thangvlq");

            entity.HasIndex(e => e.Email, "UQ__team_mem__AB6E61642CD3A6C8").IsUnique();

            entity.Property(e => e.MemberIdThangvlq).HasColumnName("member_id_Thangvlq");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("full_name");
            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("joined_at");
            entity.Property(e => e.Role)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("role");
            entity.Property(e => e.TeamIdThangvlq).HasColumnName("team_id_Thangvlq");
            entity.Property(e => e.University)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("university");

            entity.HasOne(d => d.TeamIdThangvlqNavigation).WithMany(p => p.TeamMembersThangvlqs)
                .HasForeignKey(d => d.TeamIdThangvlq)
                .HasConstraintName("fk_team_members_team_Thangvlq");
        });

        modelBuilder.Entity<TeamsHungDt>(entity =>
        {
            entity.HasKey(e => e.TeamHungDtid).HasName("PK__TeamsHun__B9BA10094FF7BACD");

            entity.ToTable("TeamsHungDT");

            entity.Property(e => e.TeamHungDtid).HasColumnName("TeamHungDTId");
            entity.Property(e => e.CategoryHungDtid).HasColumnName("CategoryHungDTId");
            entity.Property(e => e.IsApproved).HasDefaultValue(false);
            entity.Property(e => e.ProjectBudget).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(250);

            entity.HasOne(d => d.CategoryHungDt).WithMany(p => p.TeamsHungDts)
                .HasForeignKey(d => d.CategoryHungDtid)
                .HasConstraintName("FK_Teams_Categories");
        });

        modelBuilder.Entity<TeamsThangvlq>(entity =>
        {
            entity.HasKey(e => e.TeamIdThangvlq).HasName("PK__teams_Th__80FEE6F9650852AF");

            entity.ToTable("teams_Thangvlq");

            entity.HasIndex(e => e.TeamName, "UQ__teams_Th__29E35E0CA7226926").IsUnique();

            entity.Property(e => e.TeamIdThangvlq).HasColumnName("team_id_Thangvlq");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("category_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.EventSeason)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("event_season");
            entity.Property(e => e.LeaderName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("leader_name");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("team_name");
        });
        

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}