// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.ThuanVCT.Models;

public partial class CategoriesHungDt
{
    public int CategoryHungDtid { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public int? MentorId { get; set; }

    public int? Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual ICollection<TeamsHungDt> TeamsHungDts { get; set; } = new List<TeamsHungDt>();
}