// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.ThuanVCT.Models;

public partial class EventsThuanVct
{
    public int EventThuanVctid { get; set; }

    public string EventName { get; set; }

    public string Description { get; set; }

    public int Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<RoundsThuanVct> RoundsThuanVcts { get; set; } = new List<RoundsThuanVct>();
}