// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.MinhMN.Models;

public partial class JudgeScoresKhanhLq
{
    public long ScoreId { get; set; }

    public long SubmissionId { get; set; }

    public string JudgeName { get; set; }

    public string CriterionName { get; set; }

    public decimal Score { get; set; }

    public bool? IsFinalized { get; set; }

    public DateTime? ScoredAt { get; set; }

    public virtual SubmissionsKhanhLq Submission { get; set; }
}