// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.MinhMN.Models;

public partial class PrizeCategoriesSonNpx
{
    public int PrizeCategorySonNpxid { get; set; }

    public int EventSonNpxid { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<PrizesSonNpx> PrizesSonNpxes { get; set; } = new List<PrizesSonNpx>();
}