// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.ThuanVCT.Models;

public partial class PrizesSonNpx
{
    public int PrizeSonNpxid { get; set; }

    public int PrizeCategorySonNpxid { get; set; }

    public string PrizeName { get; set; }

    public decimal? ValueAmount { get; set; }

    public int? Quantity { get; set; }

    public string Requirement { get; set; }

    public bool? IsActive { get; set; }

    public virtual PrizeCategoriesSonNpx PrizeCategorySonNpx { get; set; }
}