// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.MinhMN.Models;

public partial class RoundsThuanVct
{
    public int RoundThuanVctid { get; set; }

    public int EventThuanVctid { get; set; }

    public string RoundName { get; set; }

    public DateTime Deadline { get; set; }

    public int? PromotionRule { get; set; }

    public int SortOrder { get; set; }

    public decimal? Price { get; set; }

    public virtual EventsThuanVct EventThuanVct { get; set; }
}