// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.MinhMN.Models;

public partial class SubmissionsKhanhLq
{
    public long SubmissionId { get; set; }

    public string TeamName { get; set; }

    public string RepositoryUrl { get; set; }

    public decimal? FinalScore { get; set; }

    public bool? IsApproved { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual ICollection<JudgeScoresKhanhLq> JudgeScoresKhanhLqs { get; set; } = new List<JudgeScoresKhanhLq>();
}