// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.ThuanVCT.Models;

public partial class TeamsHungDt
{
    public int TeamHungDtid { get; set; }

    public int CategoryHungDtid { get; set; }

    public string TeamName { get; set; }

    public decimal? ProjectBudget { get; set; }

    public bool? IsApproved { get; set; }

    public int? MemberCount { get; set; }

    public virtual CategoriesHungDt CategoryHungDt { get; set; }
}