// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.MinhMN.Models;

public partial class TeamsThangvlq
{
    public int TeamIdThangvlq { get; set; }

    public string TeamName { get; set; }

    public string CategoryName { get; set; }

    public string EventSeason { get; set; }

    public string LeaderName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<TeamMembersThangvlq> TeamMembersThangvlqs { get; set; } = new List<TeamMembersThangvlq>();
}