// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sealHkthon.Entities.MinhMN.Models;

public partial class TeamMembersThangvlq
{
    public int MemberIdThangvlq { get; set; }

    public int TeamIdThangvlq { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Role { get; set; }

    public string University { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual TeamsThangvlq TeamIdThangvlqNavigation { get; set; }
}